### ISSUE TITLE
1.21 on 32Bit computer?

### ISSUE THREAD

**Issue by Aruvelut-123** [Chocohead/Not-So-New#24]
I don't know if this is possible but pls let 32-bit computer play 1.21 again!

**Comment by TheMajorTechie** [comment]
This is possible even without Not So New. [Here](https://www.youtube.com/watch?v=E-IPqA61wcQ) is a video I made on running a number of games on a 32 bit system, which includes Minecraft 1.21 with some optimization mods. I've been attempting to use Not So New to bring compatibility even lower to Windows XP with the same modpack, with FerriteCore being one of the main roadblocks.

**Comment by Aruvelut-123** [comment]
Wow, that's insane! But i'm wondering if it's possible to run Minecraft 1.21 on an OS much older like Windows 2000.

**Comment by TheMajorTechie** [comment]
Potentially. Much like Windows XP has One-Core-API, Windows 2000 has BlackWingCat's Windows 2000 Extended Kernel, which _also_ is able to bring support for programs built for Windows 7. And because there is still a 32-bit Java 21 build for Windows 7 available that I've been using myself... :3

**Comment by Chocohead** [comment]
Issues with LWJGL are the biggest limiting factor from using older OSes. For XP at least you can get away with backdating STB and OpenAL, as explored in #17. If you're on 2000 I would think you'd make better progress with Extended Kernel, it might well be infeasible otherwise (given XP already gets native libraries refusing to load).

As an aside, [Liberica](https://bell-sw.com/pages/downloads/#jdk-21-lts) offer 32-bit Java 21 for Windows (and Linux). Just in case someone ends up here who doesn't actually need to use Java 8.

**Comment by WindowsVista-x64** [comment]
> Wow, that's insane! But i'm wondering if it's possible to run Minecraft 1.21 on an OS much older like Windows 2000.

I haven't tested 2000, but XP 64-bit works on 1.21 fine with 2 files switched out, and XP 32-bit works up to 1.19.2 until LWJGL limitations, which seem to be a much bigger issue. If not for those LWJGL issues, something like Windows 98 with the extended kernel could probably be able to run 1.21

This makes me wonder if a mod like this but for older LWJGL versions would be possible to do, though it'd probably be too much work

**Comment by Nukley** [comment]
You can go further back to 1.12.2 using [MiniJGL](https://github.com/Vulpovile/MiniJGL) but I'm unsure about forward. me and a friend managed to whip up MiniJGL, a fork of lwjgl 2.9.6.

I have legitimate footage of me playing Minecraft 1.5.2, unmodified, [on windows 95](https://github.com/user-attachments/assets/80566027-1f18-4cb8-be19-726f001d0b95). So whatever you can get java 8 and lwjgl 2 to run on, you can theoretically get Minecraft to run on, you just have to swap out the lwjgl jars and natives with the ones form MiniJGL.

Ideally, somebody would make a mod or two that does two things:
1. What this mod does, but for use with java 5.
2. Backports modern Minecraft to use lwjgl 2.

Meeting these two requirements opens up potential to play modern Minecraft on, not just 98, but Windows 95, assuming the usage of MiniJGL.

This would, in theory, allow usage on windows 95 with MiniJGL, MiniJGL has the tech, we just need somebody who has the mind, time and patience to use it and make it happen.

One could get a bit lazy and use [this PowerPC port of Minecraft 1.8.9](https://www.macintoshrepository.org/41761-minecraft-1-8-9-for-powerpc-g4-g5) as a base, which has some of the core libraries already ported to Java 5. I was also able to utilize this port to get 1.8.9 running on 95, due in part to MiniJGL compatibility and the creator backporting the Java version.

**Comment by Aruvelut-123** [comment]
looks like i can't get 1.21.8 runs on windows vista x64 ultimate edition. pls help.
`java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-rendering-v1' at 'net.fabricmc.fabric.impl.client.rendering.hud.HudStatusBarHeightRegistryImpl'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.FabricLoaderImpl$$Lambda$8520/1651898378.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:481)
	at net.minecraft.client.main.Main.main(Main.java:249)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: java/util/SequencedCollection
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.ClassNotFoundException: java.util.SequencedCollection
	at java.lang.ClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:216)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 12 more`

**Comment by TheMajorTechie** [comment]
> looks like i can't get 1.21.8 runs on windows vista x64 ultimate edition. pls help. `java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-rendering-v1' at 'net.fabricmc.fabric.impl.client.rendering.hud.HudStatusBarHeightRegistryImpl'! at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) at net.fabricmc.loader.impl.FabricLoaderImpl$$Lambda$8520/1651898378.apply(Unknown Source) at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) at net.minecraft.class_310.<init>(class_310.java:481) at net.minecraft.client.main.Main.main(Main.java:249) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.NoClassDefFoundError: java/util/SequencedCollection at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Unknown Source) at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ... 6 more Caused by: java.lang.ClassNotFoundException: java.util.SequencedCollection at java.lang.ClassLoader.findClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) at java.lang.ClassLoader.loadClass(Unknown Source) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:216) at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) at java.lang.ClassLoader.loadClass(Unknown Source) ... 12 more`

I think it's better you put that in a new issue rather than here. This is about running Minecraft on a 32-bit system, and you've explicitly mentioned that you're running on a 64-bit one.

**Comment by Aruvelut-123** [comment]
oh sorry

**Comment by TheMajorTechie** [comment]
Ayy nice!

**Comment by Nukley** [comment]
> > You can go further back to 1.12.2 using [MiniJGL](https://github.com/Vulpovile/MiniJGL) but I'm unsure about forward. me and a friend managed to whip up MiniJGL, a fork of lwjgl 2.9.6.
> > I have legitimate footage of me playing Minecraft 1.5.2, unmodified, [on windows 95](https://github.com/user-attachments/assets/80566027-1f18-4cb8-be19-726f001d0b95). So whatever you can get java 8 and lwjgl 2 to run on, you can theoretically get Minecraft to run on, you just have to swap out the lwjgl jars and natives with the ones form MiniJGL.
> > Ideally, somebody would make a mod or two that does two things:
> > ```
> > 1. What this mod does, but for use with java 5.
> > 
> > 2. Backports modern Minecraft to use lwjgl 2.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Meeting these two requirements opens up potential to play modern Minecraft on, not just 98, but Windows 95, assuming the usage of MiniJGL.
> > This would, in theory, allow usage on windows 95 with MiniJGL, MiniJGL has the tech, we just need somebody who has the mind, time and patience to use it and make it happen.
> > One could get a bit lazy and use [this PowerPC port of Minecraft 1.8.9](https://www.macintoshrepository.org/41761-minecraft-1-8-9-for-powerpc-g4-g5) as a base, which has some of the core libraries already ported to Java 5. I was also able to utilize this port to get 1.8.9 running on 95, due in part to MiniJGL compatibility and the creator backporting the Java version.
> 
> Hi, I noticed your video quite by accident and you know what? I decided to repeat this, but launch Minecraft already on NT 3.51! I've already posted the gameplay of the game on YouTube, although I used VESA graphics with mesa opengl32.dll but I think it will work well on a real PC. https://www.youtube.com/watch?v=zr0r48XI1Jc (you'll notice that the game crashes after entering the world, but I was able to fix the problem when I made a tutorial on how to run Minecraft on NT 3.51 if you want, you can see for yourself)

Under normal circumstances I'd never say something like this, but please contact me. A lot of the stuff you do on your channel is very in line with what I do, I feel as if we could learn from eachother.

My discord tag is the same as my github, nukley

**Comment by TheMajorTechie** [comment]
I'd also be interested in the goings-on of that sorta stuff. One of if not the only barriers preventing modern Minecraft from running on, say, an original Pentium, is LWJGL3.

**Comment by mc665** [comment]
> You can go further back to 1.12.2 using [MiniJGL](https://github.com/Vulpovile/MiniJGL) but I'm unsure about forward. me and a friend managed to whip up MiniJGL, a fork of lwjgl 2.9.6.
> 
> I have legitimate footage of me playing Minecraft 1.5.2, unmodified, [on windows 95](https://github.com/user-attachments/assets/80566027-1f18-4cb8-be19-726f001d0b95). So whatever you can get java 8 and lwjgl 2 to run on, you can theoretically get Minecraft to run on, you just have to swap out the lwjgl jars and natives with the ones form MiniJGL.
> 
> Ideally, somebody would make a mod or two that does two things:
> 
> 1. What this mod does, but for use with java 5.
> 2. Backports modern Minecraft to use lwjgl 2.
> 
> Meeting these two requirements opens up potential to play modern Minecraft on, not just 98, but Windows 95, assuming the usage of MiniJGL.
> 
> This would, in theory, allow usage on windows 95 with MiniJGL, MiniJGL has the tech, we just need somebody who has the mind, time and patience to use it and make it happen.
> 
> One could get a bit lazy and use [this PowerPC port of Minecraft 1.8.9](https://www.macintoshrepository.org/41761-minecraft-1-8-9-for-powerpc-g4-g5) as a base, which has some of the core libraries already ported to Java 5. I was also able to utilize this port to get 1.8.9 running on 95, due in part to MiniJGL compatibility and the creator backporting the Java version.

Upgrading to Windows 98, you can even run Minecraft 1.21 by patching the glfw(32).dll file and using the not-so-new mod. I successfully ran 1.18.2 on Windows 98 using the pre-patched file SalC1 used in an old video of his... , but after Minecraft upgraded to the newer lwjgl 3.2.2, that patched file became outdated and the modern Minecraft, although it starts, will crash due to missing some modules.
btw, I only used the pre-patched file; I don't know how to patch it myself lol

**Comment by TimofeyLednev** [comment]
> > You can go further back to 1.12.2 using [MiniJGL](https://github.com/Vulpovile/MiniJGL) but I'm unsure about forward. me and a friend managed to whip up MiniJGL, a fork of lwjgl 2.9.6.
> > I have legitimate footage of me playing Minecraft 1.5.2, unmodified, [on windows 95](https://github.com/user-attachments/assets/80566027-1f18-4cb8-be19-726f001d0b95). So whatever you can get java 8 and lwjgl 2 to run on, you can theoretically get Minecraft to run on, you just have to swap out the lwjgl jars and natives with the ones form MiniJGL.
> > Ideally, somebody would make a mod or two that does two things:
> > 
> > 1. What this mod does, but for use with java 5.
> > 2. Backports modern Minecraft to use lwjgl 2.
> > 
> > Meeting these two requirements opens up potential to play modern Minecraft on, not just 98, but Windows 95, assuming the usage of MiniJGL.
> > This would, in theory, allow usage on windows 95 with MiniJGL, MiniJGL has the tech, we just need somebody who has the mind, time and patience to use it and make it happen.
> > One could get a bit lazy and use [this PowerPC port of Minecraft 1.8.9](https://www.macintoshrepository.org/41761-minecraft-1-8-9-for-powerpc-g4-g5) as a base, which has some of the core libraries already ported to Java 5. I was also able to utilize this port to get 1.8.9 running on 95, due in part to MiniJGL compatibility and the creator backporting the Java version.
> 
> Upgrading to Windows 98, you can even run Minecraft 1.21 by patching the glfw(32).dll file and using the not-so-new mod. I successfully ran 1.18.2 on Windows 98 using the pre-patched file SalC1 used in an old video of his... , but after Minecraft upgraded to the newer lwjgl 3.2.2, that patched file became outdated and the modern Minecraft, although it starts, will crash due to missing some modules. btw, I only used the pre-patched file; I don't know how to patch it myself lol

Do you have any proof that you ran 1.18.2 on Windows 98?

**Comment by mc665** [comment]
> > > You can go further back to 1.12.2 using [MiniJGL](https://github.com/Vulpovile/MiniJGL) but I'm unsure about forward. me and a friend managed to whip up MiniJGL, a fork of lwjgl 2.9.6.
> > > I have legitimate footage of me playing Minecraft 1.5.2, unmodified, [on windows 95](https://github.com/user-attachments/assets/80566027-1f18-4cb8-be19-726f001d0b95). So whatever you can get java 8 and lwjgl 2 to run on, you can theoretically get Minecraft to run on, you just have to swap out the lwjgl jars and natives with the ones form MiniJGL.
> > > Ideally, somebody would make a mod or two that does two things:
> > > 
> > > 1. What this mod does, but for use with java 5.
> > > 2. Backports modern Minecraft to use lwjgl 2.
> > > 
> > > Meeting these two requirements opens up potential to play modern Minecraft on, not just 98, but Windows 95, assuming the usage of MiniJGL.
> > > This would, in theory, allow usage on windows 95 with MiniJGL, MiniJGL has the tech, we just need somebody who has the mind, time and patience to use it and make it happen.
> > > One could get a bit lazy and use [this PowerPC port of Minecraft 1.8.9](https://www.macintoshrepository.org/41761-minecraft-1-8-9-for-powerpc-g4-g5) as a base, which has some of the core libraries already ported to Java 5. I was also able to utilize this port to get 1.8.9 running on 95, due in part to MiniJGL compatibility and the creator backporting the Java version.
> > 
> > 
> > Upgrading to Windows 98, you can even run Minecraft 1.21 by patching the glfw(32).dll file and using the not-so-new mod. I successfully ran 1.18.2 on Windows 98 using the pre-patched file SalC1 used in an old video of his... , but after Minecraft upgraded to the newer lwjgl 3.2.2, that patched file became outdated and the modern Minecraft, although it starts, will crash due to missing some modules. btw, I only used the pre-patched file; I don't know how to patch it myself lol
> 
> Do you have any proof that you ran 1.18.2 on Windows 98?

https://www.youtube.com/watch?v=q9Y3OxhAM_o
Despite using patchmem, the game frequently crashes, seemingly because the system only has 1 GB of RAM available.
btw my discord is noob_lol_67138_30609

**Comment by TimofeyLednev** [comment]
> > > > You can go further back to 1.12.2 using [MiniJGL](https://github.com/Vulpovile/MiniJGL) but I'm unsure about forward. me and a friend managed to whip up MiniJGL, a fork of lwjgl 2.9.6.
> > > > I have legitimate footage of me playing Minecraft 1.5.2, unmodified, [on windows 95](https://github.com/user-attachments/assets/80566027-1f18-4cb8-be19-726f001d0b95). So whatever you can get java 8 and lwjgl 2 to run on, you can theoretically get Minecraft to run on, you just have to swap out the lwjgl jars and natives with the ones form MiniJGL.
> > > > Ideally, somebody would make a mod or two that does two things:
> > > > 
> > > > 1. What this mod does, but for use with java 5.
> > > > 2. Backports modern Minecraft to use lwjgl 2.
> > > > 
> > > > Meeting these two requirements opens up potential to play modern Minecraft on, not just 98, but Windows 95, assuming the usage of MiniJGL.
> > > > This would, in theory, allow usage on windows 95 with MiniJGL, MiniJGL has the tech, we just need somebody who has the mind, time and patience to use it and make it happen.
> > > > One could get a bit lazy and use [this PowerPC port of Minecraft 1.8.9](https://www.macintoshrepository.org/41761-minecraft-1-8-9-for-powerpc-g4-g5) as a base, which has some of the core libraries already ported to Java 5. I was also able to utilize this port to get 1.8.9 running on 95, due in part to MiniJGL compatibility and the creator backporting the Java version.
> > > 
> > > 
> > > Upgrading to Windows 98, you can even run Minecraft 1.21 by patching the glfw(32).dll file and using the not-so-new mod. I successfully ran 1.18.2 on Windows 98 using the pre-patched file SalC1 used in an old video of his... , but after Minecraft upgraded to the newer lwjgl 3.2.2, that patched file became outdated and the modern Minecraft, although it starts, will crash due to missing some modules. btw, I only used the pre-patched file; I don't know how to patch it myself lol
> > 
> > Do you have any proof that you ran 1.18.2 on Windows 98?
> 
> https://www.youtube.com/watch?v=q9Y3OxhAM_o

This is very cool

**Comment by mc665** [comment]
> > > > > You can go further back to 1.12.2 using [MiniJGL](https://github.com/Vulpovile/MiniJGL) but I'm unsure about forward. me and a friend managed to whip up MiniJGL, a fork of lwjgl 2.9.6.
> > > > > I have legitimate footage of me playing Minecraft 1.5.2, unmodified, [on windows 95](https://github.com/user-attachments/assets/80566027-1f18-4cb8-be19-726f001d0b95). So whatever you can get java 8 and lwjgl 2 to run on, you can theoretically get Minecraft to run on, you just have to swap out the lwjgl jars and natives with the ones form MiniJGL.
> > > > > Ideally, somebody would make a mod or two that does two things:
> > > > > 
> > > > > 1. What this mod does, but for use with java 5.
> > > > > 2. Backports modern Minecraft to use lwjgl 2.
> > > > > 
> > > > > Meeting these two requirements opens up potential to play modern Minecraft on, not just 98, but Windows 95, assuming the usage of MiniJGL.
> > > > > This would, in theory, allow usage on windows 95 with MiniJGL, MiniJGL has the tech, we just need somebody who has the mind, time and patience to use it and make it happen.
> > > > > One could get a bit lazy and use [this PowerPC port of Minecraft 1.8.9](https://www.macintoshrepository.org/41761-minecraft-1-8-9-for-powerpc-g4-g5) as a base, which has some of the core libraries already ported to Java 5. I was also able to utilize this port to get 1.8.9 running on 95, due in part to MiniJGL compatibility and the creator backporting the Java version.
> > > > 
> > > > 
> > > > Upgrading to Windows 98, you can even run Minecraft 1.21 by patching the glfw(32).dll file and using the not-so-new mod. I successfully ran 1.18.2 on Windows 98 using the pre-patched file SalC1 used in an old video of his... , but after Minecraft upgraded to the newer lwjgl 3.2.2, that patched file became outdated and the modern Minecraft, although it starts, will crash due to missing some modules. btw, I only used the pre-patched file; I don't know how to patch it myself lol
> > > 
> > > 
> > > Do you have any proof that you ran 1.18.2 on Windows 98?
> > 
> > 
> > https://www.youtube.com/watch?v=q9Y3OxhAM_o
> 
> This is very cool

Do you have any ideas on how to modify glfw32.dll?

**Comment by TimofeyLednev** [comment]
> > > > > > You can go further back to 1.12.2 using [MiniJGL](https://github.com/Vulpovile/MiniJGL) but I'm unsure about forward. me and a friend managed to whip up MiniJGL, a fork of lwjgl 2.9.6.
> > > > > > I have legitimate footage of me playing Minecraft 1.5.2, unmodified, [on windows 95](https://github.com/user-attachments/assets/80566027-1f18-4cb8-be19-726f001d0b95). So whatever you can get java 8 and lwjgl 2 to run on, you can theoretically get Minecraft to run on, you just have to swap out the lwjgl jars and natives with the ones form MiniJGL.
> > > > > > Ideally, somebody would make a mod or two that does two things:
> > > > > > 
> > > > > > 1. What this mod does, but for use with java 5.
> > > > > > 2. Backports modern Minecraft to use lwjgl 2.
> > > > > > 
> > > > > > Meeting these two requirements opens up potential to play modern Minecraft on, not just 98, but Windows 95, assuming the usage of MiniJGL.
> > > > > > This would, in theory, allow usage on windows 95 with MiniJGL, MiniJGL has the tech, we just need somebody who has the mind, time and patience to use it and make it happen.
> > > > > > One could get a bit lazy and use [this PowerPC port of Minecraft 1.8.9](https://www.macintoshrepository.org/41761-minecraft-1-8-9-for-powerpc-g4-g5) as a base, which has some of the core libraries already ported to Java 5. I was also able to utilize this port to get 1.8.9 running on 95, due in part to MiniJGL compatibility and the creator backporting the Java version.
> > > > > 
> > > > > 
> > > > > Upgrading to Windows 98, you can even run Minecraft 1.21 by patching the glfw(32).dll file and using the not-so-new mod. I successfully ran 1.18.2 on Windows 98 using the pre-patched file SalC1 used in an old video of his... , but after Minecraft upgraded to the newer lwjgl 3.2.2, that patched file became outdated and the modern Minecraft, although it starts, will crash due to missing some modules. btw, I only used the pre-patched file; I don't know how to patch it myself lol
> > > > 
> > > > 
> > > > Do you have any proof that you ran 1.18.2 on Windows 98?
> > > 
> > > 
> > > https://www.youtube.com/watch?v=q9Y3OxhAM_o
> > 
> > 
> > This is very cool
> 
> Do you have any ideas on how to modify glfw32.dll?

Well, my solution:
1. Port LWJGL 3 to GLFW 2
or
2. Port GLFW 3 to Windows 9x/NT

**Comment by TimofeyLednev** [comment]
> > > > > > > You can go further back to 1.12.2 using [MiniJGL](https://github.com/Vulpovile/MiniJGL) but I'm unsure about forward. me and a friend managed to whip up MiniJGL, a fork of lwjgl 2.9.6.
> > > > > > > I have legitimate footage of me playing Minecraft 1.5.2, unmodified, [on windows 95](https://github.com/user-attachments/assets/80566027-1f18-4cb8-be19-726f001d0b95). So whatever you can get java 8 and lwjgl 2 to run on, you can theoretically get Minecraft to run on, you just have to swap out the lwjgl jars and natives with the ones form MiniJGL.
> > > > > > > Ideally, somebody would make a mod or two that does two things:
> > > > > > > 
> > > > > > > 1. What this mod does, but for use with java 5.
> > > > > > > 2. Backports modern Minecraft to use lwjgl 2.
> > > > > > > 
> > > > > > > Meeting these two requirements opens up potential to play modern Minecraft on, not just 98, but Windows 95, assuming the usage of MiniJGL.
> > > > > > > This would, in theory, allow usage on windows 95 with MiniJGL, MiniJGL has the tech, we just need somebody who has the mind, time and patience to use it and make it happen.
> > > > > > > One could get a bit lazy and use [this PowerPC port of Minecraft 1.8.9](https://www.macintoshrepository.org/41761-minecraft-1-8-9-for-powerpc-g4-g5) as a base, which has some of the core libraries already ported to Java 5. I was also able to utilize this port to get 1.8.9 running on 95, due in part to MiniJGL compatibility and the creator backporting the Java version.
> > > > > > 
> > > > > > 
> > > > > > Upgrading to Windows 98, you can even run Minecraft 1.21 by patching the glfw(32).dll file and using the not-so-new mod. I successfully ran 1.18.2 on Windows 98 using the pre-patched file SalC1 used in an old video of his... , but after Minecraft upgraded to the newer lwjgl 3.2.2, that patched file became outdated and the modern Minecraft, although it starts, will crash due to missing some modules. btw, I only used the pre-patched file; I don't know how to patch it myself lol
> > > > > 
> > > > > 
> > > > > Do you have any proof that you ran 1.18.2 on Windows 98?
> > > > 
> > > > 
> > > > https://www.youtube.com/watch?v=q9Y3OxhAM_o
> > > 
> > > 
> > > This is very cool
> > 
> > 
> > Do you have any ideas on how to modify glfw32.dll?
> 
> Well, my solution:
> 
>     1. Port LWJGL 3 to GLFW 2
>        or
> 
>     2. Port GLFW 3 to Windows 9x/NT

I think the second option will be easier
